buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://kotlin.bintray.com/kotlinx" }
        maven { url "https://maven.aliyun.com/repository/public" }
    }

    dependencies {
        classpath ('com.android.tools.build:gradle:8.6.0'){
            exclude module: 'proguard-gradle'
        }
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        maven { url "https://kotlin.bintray.com/kotlinx" }
        maven { url "https://maven.aliyun.com/repository/public" }
//        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        jcenter()
        maven { url 'https://jitpack.io' }
//        maven { url "https://maven.aliyun.com/repository/public" }
        mavenCentral()
        maven {
            url 'https://storage.googleapis.com/download.flutter.io'
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
